before_install:
- git submodule update --init --recursive
language: ruby
rvm:
- 1.9.3
env:
  global:
  - DB=mysql
  - secure: "FP139mUtrjau6f+EgsN9wt+donGPyN88RiOhhIjjxVaAdUSFN0EggprtDI7BByqSJAYuEB/IiksbXHYUozQl/wzj00WYRLm4f5Qhvdj7zO2qH2D3BxtcG04nNdCEF4tvb2ldz0BkYwjtf8O7glJpki0Jq45ydMMQUTWRx+QVG80=" # SAUCE_URL
  - TRAVIS_LAUNCHES_SAUCE_CONNECT=true # Tell the karma file that it does not need to launch Sauce connect
  - RAILS_ENV=development #default to the development server for Selenium tests
script:
- RAILS_ENV=test bundle exec rake --trace db:migrate test
- cd public/apps # Run the selenium tests
- "bundle exec ruby test/selenium/run_all.rb -p sauce_firefox_web -c http://localhost:3000"
- "bundle exec ruby test/selenium/run_all.rb -p sauce_chrome_web -c http://localhost:3000"
before_script:
- cp config/database.travis.yml config/database.yml
- mysql -e 'create database privly_test'
- mysql -e 'create database privly_development'
- bundle exec rake db:create #Creates the Database
- bundle exec rake db:schema:load #Loads the Scheme
- bundle exec rake db:seed #Seeds the DB
- "bundle exec rails server -p 3000 &" # Start the server for Selenium testing
addons:
  sauce_connect:
    username: privly
    access_key:
      secure: "tg+mgtaoK22zRKTkZbz9JdZTlWDMb+nKZNq1GyVa80YUGejf+4LAnaUt4VFNb5PrrOLMEom6OLq1s+cyWfaH/wOLX869v7bPXxrJ/9mjI+8lMWuI0x4rEPW/5Nnv33mTyICVWK/24f8edgiKfqMO9OaINkHe6qsUlIwirUzkGTI="
