before_install:
- git submodule update --init --recursive
language: ruby
rvm:
- 1.9.3
env:
  global:
  - DB=mysql
  - secure: IeHgStNKps3cHsB6NFnp3Z5OEwJJdS4nfn1hgf0qH87FoQa1u5xdaBBP69szsP318fgzhwa5gTN67ZpHtnBBrck6bMjyvcr+Yjk5pCvOgUNQPusx0whUa4hbW2yWpVxl0uMXuwodQ3Hn5nIKmrevf/8/VrsA2mT9i1PTsTUtAnc=
  - secure: RiO/V0y8b7XpsdT4eOhqwBepA+XnzNjVL9bWuy9f0SG9TaobSmcvubV9ocATW9kJzRDZpa6dvQmuW/A/0Gf+UOvPL/LRH55L5DaMHkOMuu28d5TKgMUlivFiybgm0hF04jPuW20kHFxSQK6duAv+HRnsbPeNYJFj0Lbrk9It+Kg=
script:
- RAILS_ENV=test bundle exec rake --trace db:migrate test
- "cd test/karma/ && karma start karma.conf-ci.js && cd ../../"
before_script:
- cp config/database.travis.yml config/database.yml
- mysql -e 'create database privly_test'
- cd test/karma/ ; npm install -g karma-cli ; npm install ; cd ../../
